export type * from './navigation';
export type { FilterValue, ListQuery, PagedResult, Toast } from './pagination';
export type * from './customer';
export type * from './ticket';
export type * from './knowledge';
export type * from './ai-console';
export type * from './settings';
export type * from './service-health';

import type { CustomerProfile, Order } from './customer';
import type { FollowUpTask, Message, ReplyDraft, ReviewDecision, ServiceTicket, TicketAction } from './ticket';
import type { IngestionDocumentRecord, IngestionJob, KnowledgeChunk, KnowledgeDocument, RagConfigSnapshot, RagRun, RagTestRun } from './knowledge';
import type { BusinessRule, FAQ, PolicyDoc, ReplyTemplate } from './ticket';
import type { AICapability, AIEnvironmentConfig, AIOpsStage, AuditLogRecord, CapabilityPipelineNode, EvaluationRecord, FeedbackLoopRecord, ModelRoutingSummary, PermissionBoundary, PipelineNodeModelConfig, ScenarioModelConfig } from './ai-console';
import type { ActivityLogItem, Agent, AnalyticsData, GlobalOperationLogEntry, SettingsData } from './settings';
import type { ServiceHealthSnapshot } from './service-health';

export interface ServiceHubSnapshot {
  customers: CustomerProfile[];
  orders: Order[];
  tickets: ServiceTicket[];
  messages: Message[];
  tasks: FollowUpTask[];
  faqs: FAQ[];
  replyTemplates: ReplyTemplate[];
  businessRules: BusinessRule[];
  policyDocs: PolicyDoc[];
  agents: Agent[];
  settings: SettingsData;
  analytics: AnalyticsData;
  activityLog: ActivityLogItem[];
  operationLogs: GlobalOperationLogEntry[];
  aiEnvironment: AIEnvironmentConfig;
  aiCapabilities: AICapability[];
  permissionBoundaries: PermissionBoundary[];
  guardrails: string[];
  aiOpsStages: AIOpsStage[];
  knowledgeDocuments: KnowledgeDocument[];
  knowledgeChunks: KnowledgeChunk[];
  ingestionDocuments: IngestionDocumentRecord[];
  ragConfig: RagConfigSnapshot;
  ragRuns: RagRun[];
  ragTestRuns: RagTestRun[];
  replyDrafts: ReplyDraft[];
  reviewDecisions: ReviewDecision[];
  ticketActions: TicketAction[];
  ingestionJobs: IngestionJob[];
  capabilityPipeline: CapabilityPipelineNode[];
  scenarioModelConfigs: ScenarioModelConfig[];
  pipelineNodeConfigs: PipelineNodeModelConfig[];
  modelRoutingSummary: ModelRoutingSummary;
  evaluations: EvaluationRecord[];
  feedbackLoop: FeedbackLoopRecord[];
  auditLogs: AuditLogRecord[];
  serviceHealth: ServiceHealthSnapshot;
}
